# 아이리스 품종 분류(여기부터 분류 모델!)
- github csv url: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv 


### 0. Tensorflow & Pandas 라이브러리 사용

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

### 1-1. 과거의 축적된 데이터 준비

In [2]:
# 1.과거의 데이터를 준비합니다.
file_route = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file_route)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

### 1-2. onehot-encoding
독립변수(x1 ~ x4) 4개, 종속변수(y) 1개_인데 범주형 data. <br>
y = w1x1 + w2x2 + w3x3 + w4x4 + b 등의 수식으로 표현 불가. <br>
→ HOW? 수식으로 사용할 수 있도록 바꿔주는 과정이 필요
****
모든 범주 칼럼으로 나타낸 뒤 해당되는 값에 1씩 ++ → 0 or 1: 원핫인코딩

In [3]:
iris_encoding = pd.get_dummies(iris) #범주형만 골라서 원핫인코딩 시킴
iris_encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

#### 1-2-1.칼럼 이름 출력
by. 원핫인코딩 → 독립변수 4개 & 종속변수 3개

In [4]:
print(iris_encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


###1-3. 독립변수, 종속변수 분리 

In [5]:
inde_var = iris_encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
de_var = iris_encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(inde_var.shape, de_var.shape)

(150, 4) (150, 3)


### 2. 모델 구조 생성
****
<b>- Softmax?</b> <br>
대부분의 분류 예측: 0~100의 % 수치로 표현 <br>
기존 회귀형 수식에 softmax 함수(이런 함수s: Activation, 활성화 함수)를 씌워서 0부터 1 사이의 값으로 예측하도록 함.<br>
회귀모델: Identity (y = x) <br>
분류모델: Softmax <br>
※ Sigmoid란 것도 있음_ 차이점 알아봐 <br>
<b>- Crossentropy?</b> <br>
문제에 따라 loss를 다르게 사용해야 함. 분류에 사용하는 loss. 회귀는 loss='mse'<br>
accuracy도 알 수 있음(1에 가까울수록 정확도 ↑)


In [6]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

### 3-1.데이터로 모델 학습(FIT)

In [7]:
model.fit(inde_var, de_var, epochs=1000, verbose=0)

### 3-2. 모델의 loss값 확인

In [8]:
model.fit(inde_var, de_var, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 5ms/step - loss: 0.1551 - accuracy: 0.9667
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1547 - accuracy: 0.9667
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1547 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1547 - accuracy: 0.9667
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1548 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1547 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1545 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1539 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1538 - accuracy: 0.9667
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1541 - accuracy: 0.9667


### 4-1. 모델 이용하여 예측

In [9]:
# 맨 처음 데이터 5개
print(model.predict(inde_var[:5]))
print(de_var[:5])

# 중간 데이터 5개
print(model.predict(inde_var[48:53]))
print(de_var[48:53])

# 맨 마지막 데이터 5개
print(model.predict(inde_var[-5:]))
print(de_var[-5:])


[[9.9917263e-01 8.2740129e-04 5.3179765e-08]
 [9.9564677e-01 4.3525961e-03 5.6056371e-07]
 [9.9846894e-01 1.5308600e-03 1.9841862e-07]
 [9.9638969e-01 3.6094913e-03 8.2103702e-07]
 [9.9943763e-01 5.6238263e-04 3.9354738e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
[[9.9941361e-01 5.8640173e-04 2.7744887e-08]
 [9.9840373e-01 1.5961818e-03 1.3987888e-07]
 [5.7678967e-04 9.3464530e-01 6.4777888e-02]
 [8.3576073e-04 8.4087831e-01 1.5828586e-01]
 [1.6404899e-04 8.5059637e-01 1.4923953e-01]]
    품종_setosa  품종_versicolor  품종_virginica
48          1              0             0
49          1              0             0
50          0              1             0
51          0              1             0
52          0              1             0
[[6.34145863e-07 1.11379035e-01 8.8862

### 4-2. 모델의 수식 확인(weights & bias 출력)

In [10]:
print(model.get_weights())

[array([[ 0.39180475,  0.7748072 , -0.82555586],
       [ 3.3366172 , -0.14412743, -0.8940352 ],
       [-4.020913  , -1.2706832 ,  0.36643988],
       [-3.9348903 , -0.9022655 ,  2.761381  ]], dtype=float32), array([ 2.0641441 ,  0.74019897, -1.1503401 ], dtype=float32)]
